name: Splunk HEC Plugin
services:
  frankframework:
    image: nexus.frankframework.org/frankframework:latest
    ports:
      - "8080:8080"
      - "8001:8001"
    volumes:
      - ./target/splunk-appender-7.9.6-SNAPSHOT-fatjar.jar:/opt/frank/resources/splunk-plugin.jar
      - ./src/test/resources/log4j4ibis.properties:/opt/frank/resources/log4j4ibis.properties
      - ./src/main/secrets:/opt/frank/secrets
    entrypoint: /usr/local/tomcat/bin/catalina.sh
    command:
        - jpda
        - run
    environment:
      dtap.stage: "LOC"
      log.level: INFO
      log4j.configurationFile: log4j4ibis.xml,log4j2-to-splunk.xml
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:8001
      # Configures the `Frank!Framework CredentialManager`, to load credentials from the `credentials.properties` file.
      credentialFactory.class: nl.nn.credentialprovider.PropertyFileCredentialFactory
      credentialFactory.map.properties: /opt/frank/secrets/credentials.properties

  splunk:
    image: splunk/splunk:latest
    ports:
      - "8000:8000"
      - "8088:8088"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HEC_TOKEN=abcd1234
      - SPLUNK_PASSWORD=Passw0rd
      - SPLUNK_LICENSE_URI=Free
